import React from 'react';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css';
import WhatsAppFloatButton from '@/component/FloatWhatsapp';
import FixedCallButton from '@/component/FixedCall';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
        
      </head>
      <body className={inter.className}>
      <FixedCallButton/>
        <WhatsAppFloatButton/>
        {children}
        </body>
    </html>
  );
}
